package com.example.habit.request;

import com.example.habit.enums.PaymentOptions;
import com.example.habit.enums.PaymentRequestType;
import com.example.habit.entity.User;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.math.BigDecimal;

@Setter
@Getter
@ToString
public class InitiatePaymentRequest {

    private String orderId;
    private String customerId; // generated by us
    private BigDecimal txnAmount;
    private String txnId;
    private PaymentRequestType requestType;
    private PaymentOptions paymentOptions;
    private User user;
    private String refundOrderId;
}
